{
 "title": "HW5 Demoapp Load",
 "time": { "from": "2026-01-20T15:49:30.000Z", "to": "2026-01-20T15:56:30.000Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "proj", "label": "Project Name", "query": "otus-2025-msa-project" },
   {
    "name": "ns",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   {
    "name": "db",
    "label": "DB Datname",
    "query": {
     "query": "label_values(pg_stat_database_numbackends{namespace=\"$ns\"},datname)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "1m,2m,5m,10m" },
   { "name": "query0", "query": { "query": "label_values()" } }
  ]
 },
 "panels": [
  { "title": "Мониторинг приложения", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "[APP] Latency (response time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=\"$proj\", namespace=\"$ns\"}[$rate_interval])) by (le, handler))",
     "legendFormat": "{{handler}} 99p"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"$proj\", namespace=\"$ns\"}[$rate_interval])) by (le, handler))",
     "legendFormat": "{{handler}} 95p"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{job=\"$proj\", namespace=\"$ns\"}[$rate_interval])) by (le, handler))",
     "legendFormat": "{{handler}} 50p"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(http_request_duration_seconds_bucket{job=\"$proj\", namespace=\"$ns\"}[$rate_interval])) by (le, handler))",
     "legendFormat": "{{handler}} max"
    }
   ]
  },
  {
   "title": "[APP] RPS Пользовательских запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"$proj\", namespace=\"$ns\", code!~\"5..\"}[$rate_interval])) by (method, handler, code)",
     "legendFormat": "{{method}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "[APP] Error Rate",
   "type": "timeseries",
   "description": "Количество 500ых ответов",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"$proj\", namespace=\"$ns\", code=~\"5.*\"}[$rate_interval])) by (method, handler, code)",
     "legendFormat": "{{method}} {{handler}} {{code}}"
    }
   ]
  },
  { "title": "Мониторинг ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "[INGRESS] Latency (response time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"$proj\"}[$rate_interval])) by (le, path))",
     "legendFormat": "{{path}} 99p"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"$proj\"}[$rate_interval])) by (le, path))",
     "legendFormat": "{{path}} 95p"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"$proj\"}[$rate_interval])) by (le, path))",
     "legendFormat": "{{path}} 50p"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"$proj\"}[$rate_interval])) by (le, path))",
     "legendFormat": "{{path}} max"
    }
   ]
  },
  {
   "title": "[INGRESS] RPS Пользовательских запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"$proj\", status!~\"5..\"}[$rate_interval])) by (method, path, status)",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "[INGRESS] Error Rate",
   "type": "timeseries",
   "description": "Количество 500ых ответов",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"$proj\", status=~\"5.*\"}[$rate_interval])) by (method, path, status)",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  },
  { "title": "Мониторинг k8s", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "[APP] Потребление памяти приложения",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (\n  kube_pod_info{pod=~\"$proj.*\", namespace=\"$ns\"}\n  * on (pod)\n  sum by (pod) (avg_over_time(container_memory_working_set_bytes{pod=~\"$proj.*\", namespace=\"$ns\", container!=\"POD\"}[$rate_interval]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[APP] Потребление CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by(pod) (\n  kube_pod_info{pod=~\"$proj.*\", namespace=\"$ns\"}\n  * on (pod)\n  sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~\"$proj.*\", namespace=\"$ns\", container!=\"POD\"}[$rate_interval]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Мониторинг БД", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "[DB] Количестко выполненных операций над строками",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_tup_fetched{datname=~\"$db\",namespace=\"$ns\"}[$rate_interval])) by (pod)",
     "legendFormat": "{{pod}} fetched"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_returned{datname=~\"$db\",namespace=\"$ns\"}[$rate_interval])) by (pod)",
     "legendFormat": "{{pod}} returned"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_inserted{datname=~\"$db\",namespace=\"$ns\"}[$rate_interval])) by (pod)",
     "legendFormat": "{{pod}} inserted"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_updated{datname=~\"$db\",namespace=\"$ns\"}[$rate_interval])) by (pod)",
     "legendFormat": "{{pod}} updated"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_deleted{datname=~\"$db\",namespace=\"$ns\"}[$rate_interval])) by (pod)",
     "legendFormat": "{{pod}} deleted"
    }
   ]
  },
  {
   "title": "[DB] Количество активных соединений",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=~\"$db\",namespace=\"$ns\"}",
     "legendFormat": "{{pod}} {{datname}}"
    }
   ]
  },
  {
   "title": "[DB] Время выполнения самых долгих странзакций",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max (pg_stat_activity_max_tx_duration{datname=\"$db\",namespace=~\"$ns\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}